### ISSUE TITLE
Write an import function for the wind data

### ISSUE THREAD

**Issue by ksshannon** [firelab/rxcadre#2]
Write a function that opens a csv file, parses each record, and inserts the data into a new table created in the function (hard-coded or generated from the header).  The function should also populate the appropriate values in plot_location and obs_tables.  There is an example file in test/test_data.txt (I should rename it).  Note that in the example data, the names aren't unique alone.  You have to combine the name and the event to create a unique plot.

python modules:
import csv
import sqlite3

**Comment by gcshollow** [comment]
It's all working, you can even change the project name
