### ISSUE TITLE
Implement time series graph

### ISSUE THREAD

**Issue by ksshannon** [firelab/rxcadre#5]
A time series graph should be output given arbitrary data.  For example, if wind data is uses, data for speed, direction, and gust will be passed with a time series and column names.  See:

https://github.com/ksshannon/showind/blob/master/src/showind.py

the function:

def create_time_series_image(self, data, plt_title, filename = ''):

creates a time series for the wind data.  The number of datasets should be arbitrary.

**Comment by gcshollow** [comment]
It is currently able to read a file in mixed order or imperfect headings and produce a correct time series and polar plot.  I will close this issue once I've completed testing.

**Comment by gcshollow** [comment]
Working pretty freakin' well
