### ISSUE TITLE
Add obs_disp_name to obs_table creation

### ISSUE THREAD

**Issue by ksshannon** [firelab/rxcadre#6]
See doc/table_design.md

**Comment by gcshollow** [comment]
I'm currently confused as to the value of obs_disp_name.  Presumably a file called "new_file1.csv" would receive an obs_disp_name of 'new_file1', but there is already a value in obs_table for a name (obs_table_name). According to the design document this was previously populated with a kind of description of the sensor, i.e. "Cup and Vane", but the type of sensor doesn't appear to be included in the data.  Will we parse that value separately or will it always be cup&vane?

**Comment by gcshollow** [comment]
the display names have now been added to the observation table
