### ISSUE TITLE
Combine path and filename handling

### ISSUE THREAD

**Issue by ksshannon** [firelab/rxcadre#7]
Kegan,
All paths and file names should be analagous.  The user should just be able to choose a file name anywhere.  The concept of the working directory is usually very fragile.  Also, use the os.path module for file names, that's what it's for.  See commit: 

f74bd4a1ed8ce1186ea1e301ae1b2211535f7474

for an example.

**Comment by gcshollow** [comment]
I've updated all instances of string concatenation to use os.path.  It can now import data from different directories than its own.  Did you want me to remove the whole 'current directory' thing?

**Comment by gcshollow** [comment]
There are two versions in the repository now.  One with the ability to change the directory and one without.  Both use os.path.abspath by default.  Please let me know which you prefer.

**Comment by ksshannon** [comment]
Kegan, can we just make 'Create Database' act like 'Select Database'?  Using a filepath picker?

**Comment by gcshollow** [comment]
Added a directory picker to allow for database creation anywhere and gave ownership of database filepath to RxCadre to allow for calls to the database without referencing the path again.  see 46ed78e3e5d67dd880ce37cee7fb85fca5f60358
(I'm not sure I linked the commit correctly)
